### PR TITLE
Removed env.sample contents in order to test github check

### PR DESCRIPTION
**Pull request by jethanh**
# Description

# Type of Change
- [ ] New Feature
- [X] Bug Fix
- [ ] Feature improvement

# Status
- [ ] Tested

### CODE REVIEW

**Comment by jethanh** [comment]
Testing to see if github check will pass if .env.sample is empty - It fails if .env.sample doesn't exist.

**Comment by jethanh** [comment]
looks like the default contents of .env.sample is required for this check to pass. Tested all options.

**Review by christianlewis024 — COMMENTED** [review]
Looks good

**Review by exploratum — COMMENTED** [review]
is that report file really needed to be uploaded, or should it be added to .ignore? report file: report.20200820.164924.5112.0.001.json

**Pull request merged**
